### ISSUE TITLE
code without v2c part

### ISSUE THREAD

**Issue by wilesun** [vlang/intellij-v#1]
### Describe the bug

build the code,has some problem
1.IU and CL version, can't get,replease the version to:IU-231.9414-EAP-CANDIDATE-SNAPSHOT,L-231.9414-EAP-CANDIDATE-SNAPSHOT,
2.no v2c code, can't build project 

### Expected Behavior

please add these code

### Current Behavior

e: src/main/kotlin/org/vlang/lang/psi/impl/VlangReference.kt: (75, 33): Unresolved reference: VlangCodeFragment
e: src/main/kotlin/org/vlang/lang/psi/impl/VlangReference.kt: (701, 50): Unresolved reference: VlangDebuggerExpressionCodeFragment
e: src/main/kotlin/org/vlang/lang/psi/impl/VlangReference.kt: (887, 35): Unresolved reference: VlangCodeFragment
e: src/main/kotlin/org/vlang/lang/psi/impl/VlangReference.kt: (889, 36): Unresolved reference: VlangCodeFragment
e: src/main/kotlin/org/vlang/lang/psi/impl/VlangReference.kt: (894, 58): Unresolved reference: VlangCodeFragment

### Reproduction Steps

idea open the project and build

### Environment details (`v doctor` output)

V 0.4.5 b01e091

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

idea 2023.3.6+jdk 1.17

**Comment by Krotki** [comment]
This should be fixed with #2, but it targets 2024.1.
