### ISSUE TITLE
import os results in circular dependency

### ISSUE THREAD

**Issue by pd-giz-dave** [vlang/intellij-v#14]
### Describe the bug

`import os` results in a circular dependency notice.
AFAICT due to the presence of the `asset` module nested in the `os` folder hierarchy which itself does an `import os`

### Expected Behavior

Not to have a circular dependency notice.

### Current Behavior

Results in `Circular import detected`

### Reproduction Steps

`import os`

### Possible Solution

Detect the `module asset` line in the asset.v file and thus not consider it part of the `os` module.

### Environment details (`v doctor` output)

```
dave@dave-mini-pc~ >>> v doctor
V full version: V 0.4.8 3108820.164c681
OS: linux, "EndeavourOS Linux"
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 5800H with Radeon Graphics

getwd: /home/dave
vexe: /home/dave/v/v
vexe mtime: 2024-11-04 20:00:08

vroot: OK, value: /home/dave/v
VMODULES: OK, value: /home/dave/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.47.0
Git vroot status: weekly.2024.37-368-g164c6817 (23 commit(s) behind V master)
.git/config present: true

CC version: cc (GCC) 14.2.1 20240910
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9
```

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

IDEA CLion v2024.2.3

### Plugin Version

0.0.1-beta.6

**Comment by Krotki** [comment]
This error should be fixed in the next release, which in fact is in progress right now (waiting for approval).

It actually happened due to test files in vlib importing a given module, so almost all vlib modules where marked as circular dependency.

Please test and if still happening with new version, please reopen.

**Comment by pd-giz-dave** [comment]
Fixed. Great. Thanks.
PS: I had to install the release candidate version of CLion - 243
