### ISSUE TITLE
Static member issues

### ISSUE THREAD

**Issue by CoolCoderSuper** [vlang/intellij-v#6]
### Describe the bug

![image](https://github.com/vlang/intellij-v/assets/76707331/e1bc763d-2796-464b-8b53-de52c4c3a7e5)
As you can see it incorrectly errors on a static method.

### Expected Behavior

Have proper language feature since it does compile.

### Current Behavior

Gives incorrect diagnostics

### Reproduction Steps

Just have a static method

### Environment details (`v doctor` output)

V full version: V 0.4.6 a92700e.096226b
OS: windows, Microsoft Windows 11 Pro v26120 64-bit
Processor: 20 cpus, 64bit, little endian, 

getwd: C:\CodingCool\Code\Projects\vlangtesting
vexe: C:\CodingCool\Code\Projects\ThirdParty\vlang\v\v.exe
vexe mtime: 2024-06-05 20:46:36

vroot: OK, value: C:\CodingCool\Code\Projects\ThirdParty\vlang\v
VMODULES: OK, value: C:\Users\josep\.vmodules
VTMP: OK, value: C:\Users\josep\AppData\Local\Temp\v_0

Git version: git version 2.45.1.windows.1
Git vroot status: weekly.2023.26-2279-g096226bf
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

CLion

### Plugin Version

0.0.1-beta.5

**Comment by Krotki** [comment]
Version 0.0.1-beta.6 should fix the parser and should no longer be recognized as an error.

But there is no intellisence and indexing support yet.

**Comment by CoolCoderSuper** [comment]
Awesome is it possible to target IntelliJ 2024.2 instead of .1

**Comment by Krotki** [comment]
Yes it is already targeting 2024.2.

If you want to test it already just:
1. download project
2. `./gradlew build -x test`
3. go for coffee (it will take a while)
4. in intellij open settings > plugins
5. select cogwheel icon and install from disk > select <project dir>/build/distributions/IntelliJ V-0.0.1-beta.6.zip

**Comment by Krotki** [comment]
Closing the issue. If you notice any problems with syntax highlighting, please reopen.
